import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  /* Base */
  screen: { flex: 1, backgroundColor: '#F8FAFC' },
  scroll: { paddingBottom: 20 },

  /* Header  */
  headerBg: { height: 160, position: 'relative' },
  headerBgImage: { resizeMode: 'cover' },
  headerOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(2,6,23,0.35)' },
  headerContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 40,
    justifyContent: 'flex-end',
    paddingBottom: 16,
  },
  headerTitle: { color: '#FFFFFF', fontSize: 22, fontWeight: '900' },
  headerSub: { color: '#E5E7EB', marginTop: 2, fontWeight: '700' },

  headerChipsRow: { flexDirection: 'row', gap: 8, marginTop: 10, alignItems: 'center' },

  /* Chips */
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  chipPrimary: { backgroundColor: '#4F46E5', borderColor: '#4338CA' },
  chipIcon: { marginRight: 6 },
  chipText: { color: '#1E293B', fontWeight: '700', fontSize: 12 },
  chipTextPrimary: { color: '#EEF2FF', fontWeight: '800' },

  /* Badges por estado */
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
  },
  badgeGreen: { backgroundColor: '#D1FAE5', borderColor: '#A7F3D0' },
  badgeYellow: { backgroundColor: '#FEF9C3', borderColor: '#FDE68A' },
  badgeBlue: { backgroundColor: '#DBEAFE', borderColor: '#BFDBFE' },
  badgeTextDark: { color: '#065F46', fontWeight: '800' },
  badgeTextWarn: { color: '#92400E', fontWeight: '800' },
  badgeTextInfo: { color: '#1E3A8A', fontWeight: '800' },

  /* Cards */
  card: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  linkRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  linkText: { color: '#4F46E5', fontWeight: '800' },
  cardTitle: { color: '#0F172A', fontWeight: '900', fontSize: 16, marginBottom: 8 },

  rowItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  label: { color: '#64748B', fontWeight: '700', width: 120 },
  value: { color: '#0F172A', fontWeight: '800', flex: 1, textAlign: 'right' },
  valueMultiline: { textAlign: 'left', lineHeight: 20 },

  /* Mini publicación */
  pubCard: { backgroundColor: '#F8FAFC', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#E5E7EB' },
  pubHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C7D2FE',
  },
  avatarLetter: { color: '#3730A3', fontWeight: '900' },
  headerText: { flex: 1 },
  autor: { color: '#0F172A', fontWeight: '800' },
  fecha: { color: '#94A3B8', fontSize: 12 },

  pubTitulo: { color: '#0F172A', fontWeight: '900', marginTop: 8 },
  pubTexto: { color: '#334155', marginTop: 6, lineHeight: 20 },
  pubImagen: { marginTop: 10, width: '100%', height: 160, borderRadius: 12 },

  tagsRow: { flexDirection: 'row', gap: 8, marginTop: 8, flexWrap: 'wrap' },
  tagChip: {
    backgroundColor: '#EEF2FF',
    color: '#3730A3',
    borderColor: '#C7D2FE',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontWeight: '800',
  },

  collabBlock: { marginTop: 10 },
  collabLabel: { color: '#334155', fontWeight: '800', marginBottom: 6 },
  collabRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  collabPill: {
    backgroundColor: '#EFF6FF',
    borderColor: '#BFDBFE',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  collabPillText: { color: '#1D4ED8', fontWeight: '800' },
  collabPillMuted: {
    backgroundColor: '#F1F5F9',
    borderColor: '#E2E8F0',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  collabPillMutedText: { color: '#475569', fontWeight: '800' },

  pubFooter: { marginTop: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  voteRow: { flexDirection: 'row', alignItems: 'center' },
  voteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  voteImage: { width: 16, height: 16 },
  voteCount: { color: '#0F172A', fontWeight: '900' },
  verMasBtn: {
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#4F46E5',
    borderWidth: 1,
    borderColor: '#4338CA',
  },
  verMasText: { color: '#FFFFFF', fontWeight: '900' },

  /* Notificar al usuario */
  notifyCard: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#0F172A',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  toRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  toLabel: { color: '#64748B', fontWeight: '700' },
  toPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#EEF2FF',
    borderColor: '#C7D2FE',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  toText: { color: '#3730A3', fontWeight: '800' },

  templatesRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  templateChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#F8FAFC',
    borderColor: '#E2E8F0',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  templateText: { color: '#334155', fontWeight: '700', maxWidth: 220 },

  notifyInput: {
    minHeight: 110,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#F8FAFC',
    padding: 12,
    textAlignVertical: 'top',
    color: '#0F172A',
    lineHeight: 20,
    fontWeight: '600',
  },

  countRow: { marginTop: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  countText: { color: '#64748B', fontWeight: '700' },

  linkPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
  },
  linkPillOn: { backgroundColor: '#D1FAE5', borderColor: '#A7F3D0' },
  linkPillOff: { backgroundColor: '#F1F5F9', borderColor: '#E2E8F0' },
  linkPillTextOn: { color: '#065F46', fontWeight: '800' },
  linkPillTextOff: { color: '#475569', fontWeight: '800' },

  sendBtn: {
    marginTop: 10,
    backgroundColor: '#4F46E5',
    borderColor: '#4338CA',
    borderWidth: 1,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  sendBtnDisabled: { opacity: 0.5 },
  sendBtnText: { color: '#FFFFFF', fontWeight: '900' },

  /* Acciones generales */
  actionsRow: { flexDirection: 'row', gap: 10, marginHorizontal: 16, marginTop: 14 },
  btn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 12,
    paddingVertical: 12,
    borderWidth: 1,
  },
  btnPrimary: { backgroundColor: '#4F46E5', borderColor: '#4338CA' },
  btnPrimaryText: { color: '#FFFFFF', fontWeight: '900' },
  btnGhost: { backgroundColor: '#EEF2FF', borderColor: 'rgba(199, 210, 254, 1)' },
  btnGhostText: { color: '#3730A3', fontWeight: '900' },
  btnNeutralText: { color: '#334155', fontWeight: '900' },
});
